package principal;

import algoritmo.AlgoritmoKruskale;
import algoritmo.AlgoritmoWelshPowell;
import grafo.Grafo;

public class PrincipalSeminario_Opcao2 {
	public static void main(String[] args) {
		executarSeminario();

	}

	public static void executarSeminario() {

		Grafo g = new Grafo();

		g.adicionarVertice("Acetona");
		g.adicionarVertice("Acetonitrila");
		g.adicionarVertice("Ácido_Acético");
		g.adicionarVertice("Ácido_Clorídrico");
		g.adicionarVertice("Ácido_Clorossulfônico");
		g.adicionarVertice("Ácido_Crômico");
		g.adicionarVertice("Ácido_Fluorídrico");
		g.adicionarVertice("Ácido_Nítrico");
		g.adicionarVertice("Ácido_Oxálico");
		g.adicionarVertice("Ácido_Perclórico");
		g.adicionarVertice("Ácido_Sulfúrico");
		g.adicionarVertice("Metais_Alcalinos_E_Alcalinoterrosos");
		g.adicionarVertice("Álcool_Amílico");
		g.adicionarVertice("Álquil_Alumínio");
		g.adicionarVertice("Amideto_De_Sódio");
		g.adicionarVertice("Amônia_Anidra");
		g.adicionarVertice("Anidrido_Acético");
		g.adicionarVertice("Anidrido_Maleico");
		g.adicionarVertice("Anilina");
		g.adicionarVertice("Azidas");
		g.adicionarVertice("Benzeno");
		g.adicionarVertice("Bromo");
		g.adicionarVertice("Carvão_Ativo");
		g.adicionarVertice("Cianetos");
		g.adicionarVertice("Cloratos");
		g.adicionarVertice("Cloreto_De_Mercúrio");
		g.adicionarVertice("Cloro");
		g.adicionarVertice("Clorofórmio");
		g.adicionarVertice("Cobre_Metálico");
		g.adicionarVertice("Éter_Etílico");
		g.adicionarVertice("Fenol");
		g.adicionarVertice("Ferrocianeto_De_Potássio");
		g.adicionarVertice("Flúor");
		g.adicionarVertice("Formaldeído");
		g.adicionarVertice("Fósforo");
		g.adicionarVertice("Hidrazina");
		g.adicionarVertice("Hidretos");
		g.adicionarVertice("Hidrocarbonetos");
		g.adicionarVertice("Hidróxido_De_Amônio");
		g.adicionarVertice("Hidroxilamina");
		g.adicionarVertice("Hipocloritos");
		g.adicionarVertice("Hipoclorito_De_Sódio");
		g.adicionarVertice("Iodo");
		g.adicionarVertice("Líquidos_Inflamáveis");
		g.adicionarVertice("Mercúrio");
		g.adicionarVertice("Nitratos");
		g.adicionarVertice("Oxalato_De_Amônio");
		g.adicionarVertice("Óxido_De_Etileno");
		g.adicionarVertice("Óxido_De_Sódio");
		g.adicionarVertice("Pentóxido_De_Fósforo");
		g.adicionarVertice("Percloratos");
		g.adicionarVertice("Perclorato_De_Potássio");
		g.adicionarVertice("Permanganato_De_Potássio");
		g.adicionarVertice("Peróxidos");
		g.adicionarVertice("Peróxido_De_Benzoíla");
		g.adicionarVertice("Peróxido_De_Hidrogênio");
		g.adicionarVertice("Peróxido_De_Sódio");
		g.adicionarVertice("Potássio");
		g.adicionarVertice("Prata_E_Seus_Sais");
		g.adicionarVertice("Sódio");
		g.adicionarVertice("Sulfetos");
		g.adicionarVertice("Sulfeto_De_Hidrogênio");
		g.adicionarVertice("Teluretos");
		g.adicionarVertice("Tetracloreto_De_Carbono");
		g.adicionarVertice("Zinco");
		g.adicionarVertice("Zircônio");

		// Verificar se está correto adicionar os vértices a seguir:
		g.adicionarVertice("Oxidantes");
		g.adicionarVertice("Ácidos");
		g.adicionarVertice("Permanganatos");
		g.adicionarVertice("Metais_Mais_Comuns");
		g.adicionarVertice("Aminas");
		g.adicionarVertice("Óxidos_Metálicos");
		g.adicionarVertice("Acetato_De_Vinila");
		g.adicionarVertice("Sulfato_De_Mercúrio");
		g.adicionarVertice("Fosfato_De_Cálcio");
		g.adicionarVertice("Carbonatos");
		g.adicionarVertice("Bases_Fortes");
		g.adicionarVertice("Materiais_Orgânicos");
		g.adicionarVertice("Água");
		g.adicionarVertice("Metais_Na_Forma_De_Pó");
		g.adicionarVertice("Naftaleno");
		g.adicionarVertice("Cânfora");
		g.adicionarVertice("Glicerina");
		g.adicionarVertice("Alcoóis");
		g.adicionarVertice("Papel");
		g.adicionarVertice("Amônia");
		g.adicionarVertice("Mercúrio_E_Seus_Sais");
		g.adicionarVertice("Peróxidos_Orgânicos");
		g.adicionarVertice("Madeira");
		g.adicionarVertice("Lítio");
		g.adicionarVertice("Magnésio");
		g.adicionarVertice("Cálcio");
		g.adicionarVertice("Dióxido_De_Carbono");
		g.adicionarVertice("Tetracloreto_De_Carbono_E_Outros_Hidrocarbonetos_Clorados");
		g.adicionarVertice("Quaisquer_Ácidos_Livres");
		g.adicionarVertice("Quaisquer_Halogênios");
		g.adicionarVertice("Aldeídos");
		g.adicionarVertice("Cetonas");
		g.adicionarVertice("Não_Usar_Água");
		g.adicionarVertice("Espuma");
		g.adicionarVertice("Extintores_De_Pó_Químico");
		g.adicionarVertice("Etílico_E_Metílico");
		g.adicionarVertice("Ácido_Fosfórico");
		g.adicionarVertice("Hidrocarbonetos_Halogenados");
		g.adicionarVertice("Ar");
		g.adicionarVertice("Hipoclorito_De_Cálcio");
		g.adicionarVertice("Odo,Bromo,Ácido_Fluorídrico");
		g.adicionarVertice("Prata");
		g.adicionarVertice("Compostos_Hidroxilados");
		g.adicionarVertice("Etileno_Glicol");
		g.adicionarVertice("Soda_Cáustica");
		g.adicionarVertice("Potassa_Cáustica");
		g.adicionarVertice("Hidróxido_De_Sódio");
		g.adicionarVertice("Piridina_E_Outras_Aminas_Terciárias");
		g.adicionarVertice("Ácido_Nítrico_Concentrado");
		g.adicionarVertice("Amoníaco");
		g.adicionarVertice("Acetileno");
		g.adicionarVertice("Butadieno");
		g.adicionarVertice("Butano");
		g.adicionarVertice("Metano");
		g.adicionarVertice("Propano");
		g.adicionarVertice("Outros_Gases_Derivados_Do_Petróleo");
		g.adicionarVertice("Carbonato_De_Sódio");
		g.adicionarVertice("Hidrogênio");
		g.adicionarVertice("Todos_Os_Agentes_Oxidantes");
		g.adicionarVertice("Sais_De_Amônio");
		g.adicionarVertice("Enxofre");
		g.adicionarVertice("Materiais_Orgânicos_Combustíveis_Finamente_-Divididos");
		g.adicionarVertice("Ácidos_Fortes");
		g.adicionarVertice("Sais_Metálicos");
		g.adicionarVertice("Álcalis_Fosfatados");
		g.adicionarVertice("Sulfitos");
		g.adicionarVertice("Sulfatos");
		g.adicionarVertice("Antimônio");
		g.adicionarVertice("Metais_Alcalinos");
		g.adicionarVertice("Alumínio");
		g.adicionarVertice("Agentes_Oxidantes_Fortes");
		g.adicionarVertice("Acido_Clorídrico");
		g.adicionarVertice("Hidróxido_De_Potássio");
		g.adicionarVertice("Compostos_Halogenados");
		g.adicionarVertice("Isolar_De_Tudo");
		g.adicionarVertice("Ácidos_Inorgânicos");
		g.adicionarVertice("Álcalis");
		g.adicionarVertice("Agentes_Redutores");
		g.adicionarVertice("Oxigênio");
		g.adicionarVertice("Qualquer_Outro_Oxidante");
		g.adicionarVertice("Hidrocarbonetos_Clorados");
		g.adicionarVertice("Propano,Gasolina");
		g.adicionarVertice("Cobre");
		g.adicionarVertice("Bronze");
		g.adicionarVertice("Latão");
		g.adicionarVertice("Óxido_De_Bário");
		g.adicionarVertice("Dióxido_De_Chumbo");
		g.adicionarVertice("Pentacloreto_E_Tricloreto_De_Fósforo");
		g.adicionarVertice("Dicromato_De_Potássio");
		g.adicionarVertice("Carvão_Ativado");
		g.adicionarVertice("Nitrometano");
		g.adicionarVertice("Óxido_De_Ferro");
		g.adicionarVertice("Nitrato_De_Amônio");
		g.adicionarVertice("Halogênios");
		g.adicionarVertice("Ácido_Fulmínico");
		g.adicionarVertice("Materiais_Orgânicos_Ou_Combustíveis_Finamente_Divididos");
		g.adicionarVertice("Bases");
		g.adicionarVertice("Perclorato_De_Magnésio");
		g.adicionarVertice("Qualquer_Ácido_Livre");
		g.adicionarVertice("Ver_Também_Em_Ácido_Perclórico_E_Cloratos");
		g.adicionarVertice("Benzaldeído");
		g.adicionarVertice("Evitar_Fricção");
		g.adicionarVertice("Armazenar_A_Baixa_Temperatura");
		g.adicionarVertice("Crômio");
		g.adicionarVertice("Ferro");
		g.adicionarVertice("Maioria_Dos_Metais_E_Seus_Sais");
		g.adicionarVertice("Materiais_Combustíveis");
		g.adicionarVertice("Qualquer_Líquido_Inflamável");
		g.adicionarVertice("Qualquer_Substância_Oxidável");
		g.adicionarVertice("Como_Etanol");
		g.adicionarVertice("Metanol");
		g.adicionarVertice("Ácido_Acético_Glaciar");
		g.adicionarVertice("Dissulfito_De_Carbono");
		g.adicionarVertice("Acetato_De_Etíla");
		g.adicionarVertice("Acetato_De_Metila");
		g.adicionarVertice("Furfural");
		g.adicionarVertice("Álcool_Etílico");
		g.adicionarVertice("Álcool_Metílico");
		g.adicionarVertice("Ácido_Tartárico");
		g.adicionarVertice("Compostos_De_Amônio");
		g.adicionarVertice("Ver_Também_Em_Metais_Alcalinos");
		g.adicionarVertice("Ácido_Nítrico_Fumegante");
		g.adicionarVertice("Gases_Oxidantes");
		g.adicionarVertice("Espuma_Ou_Extintor_De_Pó_Químico");

		g.adicionarAresta("Acetona", "Ácido_Nítrico");
		g.adicionarAresta("Acetona", "Ácido_Sulfúrico");
		g.adicionarAresta("Acetona", "Peróxido_De_Hidrogênio");
		g.adicionarAresta("Acetonitrila", "Oxidantes");
		g.adicionarAresta("Acetonitrila", "Ácidos");
		g.adicionarAresta("Ácido_Acético", "Ácido_Crômico");
		g.adicionarAresta("Ácido_Acético", "Ácido_Nítrico");
		g.adicionarAresta("Ácido_Acético", "Ácido_Perclórico");
		g.adicionarAresta("Ácido_Acético", "Peróxido_De_Hidrogênio");
		g.adicionarAresta("Ácido_Acético", "Permanganatos");
		g.adicionarAresta("Ácido_Clorídrico", "Metais_Mais_Comuns");
		g.adicionarAresta("Ácido_Clorídrico", "Aminas");
		g.adicionarAresta("Ácido_Clorídrico", "Óxidos_Metálicos");
		g.adicionarAresta("Ácido_Clorídrico", "Anidrido_Acético");
		g.adicionarAresta("Ácido_Clorídrico", "Acetato_De_Vinila");
		g.adicionarAresta("Ácido_Clorídrico", "Sulfato_De_Mercúrio");
		g.adicionarAresta("Ácido_Clorídrico", "Fosfato_De_Cálcio");
		g.adicionarAresta("Ácido_Clorídrico", "Formaldeído");
		g.adicionarAresta("Ácido_Clorídrico", "Carbonatos");
		g.adicionarAresta("Ácido_Clorídrico", "Bases_Fortes");
		g.adicionarAresta("Ácido_Clorídrico", "Ácido_Sulfúrico");
		g.adicionarAresta("Ácido_Clorídrico", "Ácido_Clorossulfônico");
		g.adicionarAresta("Ácido_Clorossulfônico", "Materiais_Orgânicos");
		g.adicionarAresta("Ácido_Clorossulfônico", "Água");
		g.adicionarAresta("Ácido_Clorossulfônico", "Metais_Na_Forma_De_Pó");
		g.adicionarAresta("Ácido_Crômico", "Ácido_Acético");
		g.adicionarAresta("Ácido_Crômico", "Naftaleno");
		g.adicionarAresta("Ácido_Crômico", "Cânfora");
		g.adicionarAresta("Ácido_Crômico", "Glicerina");
		g.adicionarAresta("Ácido_Crômico", "Alcoóis");
		g.adicionarAresta("Ácido_Crômico", "Papel");
		g.adicionarAresta("Ácido_Fluorídrico", "Amônia");
		g.adicionarAresta("Ácido_Nítrico", "Ácido_Acético");
		g.adicionarAresta("Ácido_Nítrico", "Acetona");
		g.adicionarAresta("Ácido_Nítrico", "Alcoóis");
		g.adicionarAresta("Ácido_Nítrico", "Anilina");
		g.adicionarAresta("Ácido_Nítrico", "Ácido_Crômico");
		g.adicionarAresta("Ácido_Oxálico", "Prata_E_Seus_Sais");
		g.adicionarAresta("Ácido_Oxálico", "Mercúrio_E_Seus_Sais");
		g.adicionarAresta("Ácido_Oxálico", "Peróxidos_Orgânicos");
		g.adicionarAresta("Ácido_Perclórico", "Anidrido_Acético");
		g.adicionarAresta("Ácido_Perclórico", "Alcoóis");
		g.adicionarAresta("Ácido_Perclórico", "Papel");
		g.adicionarAresta("Ácido_Perclórico", "Madeira");
		g.adicionarAresta("Ácido_Sulfúrico", "Cloratos");
		g.adicionarAresta("Ácido_Sulfúrico", "Percloratos");
		g.adicionarAresta("Ácido_Sulfúrico", "Permanganatos");
		g.adicionarAresta("Ácido_Sulfúrico", "Peróxidos_Orgânicos");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Potássio");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Lítio");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Magnésio");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Cálcio");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Dióxido_De_Carbono");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos",
				"Tetracloreto_De_Carbono_E_Outros_Hidrocarbonetos_Clorados");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Quaisquer_Ácidos_Livres");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Quaisquer_Halogênios");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Aldeídos");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Cetonas");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Não_Usar_Água");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Espuma");
		g.adicionarAresta("Metais_Alcalinos_E_Alcalinoterrosos", "Extintores_De_Pó_Químico");
		g.adicionarAresta("Álcool_Amílico", "Etílico_E_Metílico");
		g.adicionarAresta("Álcool_Amílico", "Ácido_Clorídrico");
		g.adicionarAresta("Álcool_Amílico", "Ácido_Fluorídrico");
		g.adicionarAresta("Álcool_Amílico", "Ácido_Fosfórico");
		g.adicionarAresta("Álquil_Alumínio", "Hidrocarbonetos_Halogenados");
		g.adicionarAresta("Álquil_Alumínio", "Água");
		g.adicionarAresta("Amideto_De_Sódio", "Ar");
		g.adicionarAresta("Amideto_De_Sódio", "Água");
		g.adicionarAresta("Amônia_Anidra", "Mercúrio");
		g.adicionarAresta("Amônia_Anidra", "Cloro");
		g.adicionarAresta("Amônia_Anidra", "Hipoclorito_De_Cálcio");
		g.adicionarAresta("Amônia_Anidra", "Odo,Bromo,Ácido_Fluorídrico");
		g.adicionarAresta("Amônia_Anidra", "Prata");
		g.adicionarAresta("Anidrido_Acético", "Ácido_Crômico");
		g.adicionarAresta("Anidrido_Acético", "Ácido_Nítrico");
		g.adicionarAresta("Anidrido_Acético", "Ácido_Perclórico");
		g.adicionarAresta("Anidrido_Acético", "Compostos_Hidroxilados");
		g.adicionarAresta("Anidrido_Acético", "Etileno_Glicol");
		g.adicionarAresta("Anidrido_Acético", "Peróxidos");
		g.adicionarAresta("Anidrido_Acético", "Permanganatos");
		g.adicionarAresta("Anidrido_Acético", "Soda_Cáustica");
		g.adicionarAresta("Anidrido_Acético", "Potassa_Cáustica");
		g.adicionarAresta("Anidrido_Acético", "Aminas");
		g.adicionarAresta("Anidrido_Maleico", "Hidróxido_De_Sódio");
		g.adicionarAresta("Anidrido_Maleico", "Piridina_E_Outras_Aminas_Terciárias");
		g.adicionarAresta("Anilina", "Ácido_Nítrico");
		g.adicionarAresta("Anilina", "Peróxido_De_Hidrogênio");
		g.adicionarAresta("Azidas", "Ácidos");
		g.adicionarAresta("Benzeno", "Ácido_Clorídrico");
		g.adicionarAresta("Benzeno", "Ácido_Fluorídrico");
		g.adicionarAresta("Benzeno", "Ácido_Fosfórico");
		g.adicionarAresta("Benzeno", "Ácido_Nítrico_Concentrado");
		g.adicionarAresta("Benzeno", "Peróxidos");
		g.adicionarAresta("Bromo", "Amoníaco");
		g.adicionarAresta("Bromo", "Acetileno");
		g.adicionarAresta("Bromo", "Butadieno");
		g.adicionarAresta("Bromo", "Butano");
		g.adicionarAresta("Bromo", "Metano");
		g.adicionarAresta("Bromo", "Propano");
		g.adicionarAresta("Bromo", "Outros_Gases_Derivados_Do_Petróleo");
		g.adicionarAresta("Bromo", "Carbonato_De_Sódio");
		g.adicionarAresta("Bromo", "Benzeno");
		g.adicionarAresta("Bromo", "Metais_Na_Forma_De_Pó");
		g.adicionarAresta("Bromo", "Hidrogênio");
		g.adicionarAresta("Carvão_Ativo", "Hipoclorito_De_Cálcio");
		g.adicionarAresta("Carvão_Ativo", "Todos_Os_Agentes_Oxidantes");
		g.adicionarAresta("Cianetos", "Ácidos");
		g.adicionarAresta("Cloratos", "Sais_De_Amônio");
		g.adicionarAresta("Cloratos", "Ácidos");
		g.adicionarAresta("Cloratos", "Metais_Na_Forma_De_Pó");
		g.adicionarAresta("Cloratos", "Enxofre");
		g.adicionarAresta("Cloratos", "Materiais_Orgânicos_Combustíveis_Finamente_-Divididos");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Ácidos_Fortes");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Amoníaco");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Carbonatos");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Sais_Metálicos");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Álcalis_Fosfatados");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Sulfitos");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Sulfatos");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Bromo");
		g.adicionarAresta("Cloreto_De_Mercúrio", "Antimônio");
		g.adicionarAresta("Cloro", "Amoníaco");
		g.adicionarAresta("Cloro", "Acetileno");
		g.adicionarAresta("Cloro", "Butadieno");
		g.adicionarAresta("Cloro", "Butano");
		g.adicionarAresta("Cloro", "Propano");
		g.adicionarAresta("Cloro", "Metano");
		g.adicionarAresta("Cloro", "Outros_Gases_Derivados_Do_Petróleo");
		g.adicionarAresta("Cloro", "Hidrogênio");
		g.adicionarAresta("Cloro", "Carbonato_De_Sódio");
		g.adicionarAresta("Cloro", "Benzeno");
		g.adicionarAresta("Cloro", "Metais_Na_Forma_De_Pó");
		g.adicionarAresta("Clorofórmio", "Bases_Fortes");
		g.adicionarAresta("Clorofórmio", "Metais_Alcalinos");
		g.adicionarAresta("Clorofórmio", "Alumínio");
		g.adicionarAresta("Clorofórmio", "Magnésio");
		g.adicionarAresta("Clorofórmio", "Agentes_Oxidantes_Fortes");
		g.adicionarAresta("Cobre_Metálico", "Acetileno");
		g.adicionarAresta("Cobre_Metálico", "Peróxido_De_Hidrogênio");
		g.adicionarAresta("Cobre_Metálico", "Azidas");
		g.adicionarAresta("Éter_Etílico", "Acido_Clorídrico");
		g.adicionarAresta("Éter_Etílico", "Ácido_Fluorídrico");
		g.adicionarAresta("Éter_Etílico", "Ácido_Sulfúrico");
		g.adicionarAresta("Éter_Etílico", "Ácido_Fosfórico");
		g.adicionarAresta("Fenol", "Hidróxido_De_Sódio");
		g.adicionarAresta("Fenol", "Hidróxido_De_Potássio");
		g.adicionarAresta("Fenol", "Compostos_Halogenados");
		g.adicionarAresta("Fenol", "Aldeídos");
		g.adicionarAresta("Ferrocianeto_De_Potássio", "Ácidos_Fortes");
		g.adicionarAresta("Flúor", "Isolar_De_Tudo");
		g.adicionarAresta("Formaldeído", "Ácidos_Inorgânicos");
		g.adicionarAresta("Fósforo", "Ar");
		g.adicionarAresta("Fósforo", "Álcalis");
		g.adicionarAresta("Fósforo", "Agentes_Redutores");
		g.adicionarAresta("Fósforo", "Oxigênio");
		g.adicionarAresta("Hidrazina", "Peróxido_De_Hidrogênio");
		g.adicionarAresta("Hidrazina", "Ácido_Nítrico");
		g.adicionarAresta("Hidrazina", "Qualquer_Outro_Oxidante");
		g.adicionarAresta("Hidretos", "Água");
		g.adicionarAresta("Hidretos", "Ar");
		g.adicionarAresta("Hidretos", "Dióxido_De_Carbono");
		g.adicionarAresta("Hidretos", "Hidrocarbonetos_Clorados");
		g.adicionarAresta("Hidrocarbonetos", "Butano");
		g.adicionarAresta("Hidrocarbonetos", "Propano,Gasolina");
		g.adicionarAresta("Hidrocarbonetos", "Flúor");
		g.adicionarAresta("Hidrocarbonetos", "Cloro");
		g.adicionarAresta("Hidrocarbonetos", "Bromo");
		g.adicionarAresta("Hidrocarbonetos", "Ácido_Crômico");
		g.adicionarAresta("Hidrocarbonetos", "Peróxidos");
		g.adicionarAresta("Hidróxido_De_Amônio", "Ácidos_Fortes");
		g.adicionarAresta("Hidróxido_De_Amônio", "Metais_Alcalinos");
		g.adicionarAresta("Hidróxido_De_Amônio", "Agentes_Oxidantes_Fortes");
		g.adicionarAresta("Hidróxido_De_Amônio", "Bromo");
		g.adicionarAresta("Hidróxido_De_Amônio", "Cloro");
		g.adicionarAresta("Hidróxido_De_Amônio", "Alumínio");
		g.adicionarAresta("Hidróxido_De_Amônio", "Cobre");
		g.adicionarAresta("Hidróxido_De_Amônio", "Bronze");
		g.adicionarAresta("Hidróxido_De_Amônio", "Latão");
		g.adicionarAresta("Hidróxido_De_Amônio", "Mercúrio");
		g.adicionarAresta("Hidroxilamina", "Óxido_De_Bário");
		g.adicionarAresta("Hidroxilamina", "Dióxido_De_Chumbo");
		g.adicionarAresta("Hidroxilamina", "Pentacloreto_E_Tricloreto_De_Fósforo");
		g.adicionarAresta("Hidroxilamina", "Zinco");
		g.adicionarAresta("Hidroxilamina", "Dicromato_De_Potássio");
		g.adicionarAresta("Hipocloritos", "Ácidos");
		g.adicionarAresta("Hipocloritos", "Carvão_Ativado");
		g.adicionarAresta("Hipoclorito_De_Sódio", "Fenol");
		g.adicionarAresta("Hipoclorito_De_Sódio", "Glicerina");
		g.adicionarAresta("Hipoclorito_De_Sódio", "Nitrometano");
		g.adicionarAresta("Hipoclorito_De_Sódio", "Óxido_De_Ferro");
		g.adicionarAresta("Hipoclorito_De_Sódio", "Amoníaco");
		g.adicionarAresta("Hipoclorito_De_Sódio", "Carvão_Ativado");
		g.adicionarAresta("Iodo", "Acetileno");
		g.adicionarAresta("Iodo", "Hidrogênio");
		g.adicionarAresta("Líquidos_Inflamáveis", "Nitrato_De_Amônio");
		g.adicionarAresta("Líquidos_Inflamáveis", "Ácido_Crômico");
		g.adicionarAresta("Líquidos_Inflamáveis", "Peróxido_De_Hidrogênio");
		g.adicionarAresta("Líquidos_Inflamáveis", "Ácido_Nítrico");
		g.adicionarAresta("Líquidos_Inflamáveis", "Peróxido_De_Sódio");
		g.adicionarAresta("Líquidos_Inflamáveis", "Halogênios");
		g.adicionarAresta("Mercúrio", "Acetileno");
		g.adicionarAresta("Mercúrio", "Ácido_Fulmínico");
		g.adicionarAresta("Mercúrio", "Amônia");
		g.adicionarAresta("Mercúrio", "Ácido_Oxálico");
		g.adicionarAresta("Nitratos", "Ácidos");
		g.adicionarAresta("Nitratos", "Metais_Na_Forma_De_Pó");
		g.adicionarAresta("Nitratos", "Líquidos_Inflamáveis");
		g.adicionarAresta("Nitratos", "Cloratos");
		g.adicionarAresta("Nitratos", "Enxofre");
		g.adicionarAresta("Nitratos", "Materiais_Orgânicos_Ou_Combustíveis_Finamente_Divididos");
		g.adicionarAresta("Nitratos", "Ácido_Sulfúrico");
		g.adicionarAresta("Oxalato_De_Amônio", "Ácidos_Fortes");
		g.adicionarAresta("Óxido_De_Etileno", "Ácidos");
		g.adicionarAresta("Óxido_De_Etileno", "Bases");
		g.adicionarAresta("Óxido_De_Etileno", "Cobre");
		g.adicionarAresta("Óxido_De_Etileno", "Perclorato_De_Magnésio");
		g.adicionarAresta("Óxido_De_Sódio", "Água");
		g.adicionarAresta("Óxido_De_Sódio", "Qualquer_Ácido_Livre");
		g.adicionarAresta("Pentóxido_De_Fósforo", "Alcoóis");
		g.adicionarAresta("Pentóxido_De_Fósforo", "Bases_Fortes");
		g.adicionarAresta("Pentóxido_De_Fósforo", "Água");
		g.adicionarAresta("Percloratos", "Ácidos");
		g.adicionarAresta("Perclorato_De_Potássio", "Ácidos");
		g.adicionarAresta("Perclorato_De_Potássio", "Ver_Também_Em_Ácido_Perclórico_E_Cloratos");
		g.adicionarAresta("Permanganato_De_Potássio", "Glicerina");
		g.adicionarAresta("Permanganato_De_Potássio", "Etileno_Glicol");
		g.adicionarAresta("Permanganato_De_Potássio", "Benzaldeído");
		g.adicionarAresta("Permanganato_De_Potássio", "Qualquer_Ácido_Livre");
		g.adicionarAresta("Permanganato_De_Potássio", "Ácido_Sulfúrico");
		g.adicionarAresta("Peróxidos", "Ácidos");
		g.adicionarAresta("Peróxidos", "Evitar_Fricção");
		g.adicionarAresta("Peróxidos", "Armazenar_A_Baixa_Temperatura");
		g.adicionarAresta("Peróxido_De_Benzoíla", "Clorofórmio");
		g.adicionarAresta("Peróxido_De_Benzoíla", "Materiais_Orgânicos");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Cobre");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Crômio");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Ferro");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Maioria_Dos_Metais_E_Seus_Sais");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Materiais_Combustíveis");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Materiais_Orgânicos");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Qualquer_Líquido_Inflamável");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Anilina");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Nitrometano");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Alcoóis");
		g.adicionarAresta("Peróxido_De_Hidrogênio", "Acetona");
		g.adicionarAresta("Peróxido_De_Sódio", "Qualquer_Substância_Oxidável");
		g.adicionarAresta("Peróxido_De_Sódio", "Como_Etanol");
		g.adicionarAresta("Peróxido_De_Sódio", "Metanol");
		g.adicionarAresta("Peróxido_De_Sódio", "Ácido_Acético_Glaciar");
		g.adicionarAresta("Peróxido_De_Sódio", "Anidrido_Acético");
		g.adicionarAresta("Peróxido_De_Sódio", "Benzaldeído");
		g.adicionarAresta("Peróxido_De_Sódio", "Dissulfito_De_Carbono");
		g.adicionarAresta("Peróxido_De_Sódio", "Glicerina");
		g.adicionarAresta("Peróxido_De_Sódio", "Etileno_Glicol");
		g.adicionarAresta("Peróxido_De_Sódio", "Acetato_De_Etíla");
		g.adicionarAresta("Peróxido_De_Sódio", "Acetato_De_Metila");
		g.adicionarAresta("Peróxido_De_Sódio", "Furfural");
		g.adicionarAresta("Peróxido_De_Sódio", "Álcool_Etílico");
		g.adicionarAresta("Peróxido_De_Sódio", "Álcool_Metílico");
		g.adicionarAresta("Potássio", "Tetracloreto_De_Carbono");
		g.adicionarAresta("Potássio", "Dióxido_De_Carbono");
		g.adicionarAresta("Potássio", "Água");
		g.adicionarAresta("Prata_E_Seus_Sais", "Acetileno");
		g.adicionarAresta("Prata_E_Seus_Sais", "Ácido_Oxálico");
		g.adicionarAresta("Prata_E_Seus_Sais", "Ácido_Tartárico");
		g.adicionarAresta("Prata_E_Seus_Sais", "Ácido_Fulmínico");
		g.adicionarAresta("Prata_E_Seus_Sais", "Compostos_De_Amônio");
		g.adicionarAresta("Sódio", "Tetracloreto_De_Carbono");
		g.adicionarAresta("Sódio", "Dióxido_De_Carbono");
		g.adicionarAresta("Sódio", "Água");
		g.adicionarAresta("Sódio", "Ver_Também_Em_Metais_Alcalinos");
		g.adicionarAresta("Sulfetos", "Ácidos");
		g.adicionarAresta("Sulfeto_De_Hidrogênio", "Ácido_Nítrico_Fumegante");
		g.adicionarAresta("Sulfeto_De_Hidrogênio", "Gases_Oxidantes");
		g.adicionarAresta("Teluretos", "Agentes_Redutores");
		g.adicionarAresta("Tetracloreto_De_Carbono", "Sódio");
		g.adicionarAresta("Zinco", "Enxofre");
		g.adicionarAresta("Zircônio", "Água");
		g.adicionarAresta("Zircônio", "Tetracloreto_De_Carbono");
		g.adicionarAresta("Zircônio", "Espuma_Ou_Extintor_De_Pó_Químico");

		AlgoritmoWelshPowell awp = new AlgoritmoWelshPowell(g);
		awp.imprimirNumeroCromatico();

		System.out.println("Complemento:");
		awp = new AlgoritmoWelshPowell(g.getComplemento());
		awp.imprimirNumeroCromatico();


		System.out.println("PrincipalSeminario_Opcao2");
	}

	public static void executarSeminarioTestes() {
		Grafo g = new Grafo();

		g.adicionarVertice("a");
		g.adicionarVertice("b");
		g.adicionarVertice("c");
		g.adicionarVertice("d");
		g.adicionarVertice("e");
		g.adicionarVertice("f");
		g.adicionarVertice("g");
		g.adicionarVertice("h");
		g.adicionarVertice("i");

		g.adicionarAresta("a", "b", 3.8);
		g.adicionarAresta("a", "c", 6.1);
		g.adicionarAresta("a", "d", 1.4);
		g.adicionarAresta("a", "e", 0.795);
		g.adicionarAresta("a", "f", 3.0);
		g.adicionarAresta("a", "g", 5.2);
		g.adicionarAresta("a", "h", 1.3);
		g.adicionarAresta("a", "i", 1.7);
		g.adicionarAresta("b", "c", 9.3);
		g.adicionarAresta("b", "d", 5.9);
		g.adicionarAresta("b", "e", 4.9);
		g.adicionarAresta("b", "f", 7.0);
		g.adicionarAresta("b", "g", 1.7);
		g.adicionarAresta("b", "h", 5.4);
		g.adicionarAresta("b", "i", 5.6);
		g.adicionarAresta("c", "d", 8.1);
		g.adicionarAresta("c", "e", 7.1);
		g.adicionarAresta("c", "f", 9.2);
		g.adicionarAresta("c", "g", 11.0);
		g.adicionarAresta("c", "h", 6.1);
		g.adicionarAresta("c", "i", 7.8);
		g.adicionarAresta("d", "e", 0.494);
		g.adicionarAresta("d", "f", 1.7);
		g.adicionarAresta("d", "g", 6.7);
		g.adicionarAresta("d", "h", 2.1);
		g.adicionarAresta("d", "i", 0.343);
		g.adicionarAresta("e", "f", 1.8);
		g.adicionarAresta("e", "g", 6.8);
		g.adicionarAresta("e", "h", 2.3);
		g.adicionarAresta("e", "i", 0.412);
		g.adicionarAresta("f", "g", 8.6);
		g.adicionarAresta("f", "h", 3.8);
		g.adicionarAresta("f", "i", 1.4);
		g.adicionarAresta("g", "h", 6.8);
		g.adicionarAresta("g", "i", 7.1);
		g.adicionarAresta("h", "i", 2.4);

		AlgoritmoKruskale ak = new AlgoritmoKruskale(g);
		ak.imprimirArvoreGeradoraMinima();
		//
		// AlgoritmoPrimJarnik apj = new AlgoritmoPrimJarnik(g, "a");
		// apj.imprimirArvoreGeradoraMinima();

		// AlgoritmoDijkstra ad;
		//
		// for (Vertice u : g.getVertices()) {
		// ad = new AlgoritmoDijkstra(g, u.getNome());
		// ad.imprimirTabelaDistanciaCaminho();
		// }
	}
}
